server:
  port: 9091

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#    virtual-host: mshwari
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true